### ISSUE TITLE
Linux不能够显示图片，但是可以下载

### ISSUE THREAD

**Issue by colawithsauce** [tonquer/picacg-qt#121]
### 操作系统（如MacOS 10.15）
>
Archlinux

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>
电信宽带

### 问题描述（简要描述发生的问题）
>
能够下载，不能够显示图片

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>
不能加载图片，但是日志显示已经下载好，并且手动用 feh 发现图片是已经下载好了的。问题出在显示图片上面。

### 日志提交（问题截图或者日志，日志在logs目录）
>
```
2022-01-25 16:47:12,052 - connectionpool.py[line:442] - DEBUG: https://storage1.picacomic.com:443 "GET /static/fedf24b5-8a84-4f36-80ba-15ac85a4f099.png HTTP/1.1" 200 971418
2022-01-25 16:47:13,493 - user_handler.py[line:238] - DEBUG: add download cache, cachePath:/home/colawithsauce/.cache/bika/cache/618228e0c8b5084ecd231eeb/1/4.jpg
2022-01-25 16:47:13,496 - task_download.py[line:138] - ERROR: /tmp/.mount_bika_vLNHkll/usr/bin/PIL/_imaging.cpython-37m-x86_64-linux-gnu.so: ELF load command address/offset not properly aligned
Traceback (most recent call last):
  File "task/task_download.py", line 134, in HandlerTask
  File "view/read/read_view.py", line 297, in CompleteDownloadPic
  File "view/read/read_enum.py", line 68, in SetData
  File "tools/tool.py", line 233, in GetPictureSize
  File "PyInstaller/loader/pyimod03_importers.py", line 546, in exec_module
  File "PIL/Image.py", line 114, in <module>
ImportError: /tmp/.mount_bika_vLNHkll/usr/bin/PIL/_imaging.cpython-37m-x86_64-linux-gnu.so: ELF load command address/offset not properly aligned
```

### 分析
分析日志，指向了这个地方，也就是说引入包报错了
https://github.com/tonquer/picacg-qt/blob/efde9ff35f5e655618ecfb77433da918e4d3c91b/src/tools/tool.py#L233

找了一下pillow的issue页面，找到了一个相关的问题可以供参考
- https://github.com/python-pillow/Pillow/issues/4854

可能是打包的问题，也可能是 Pillow 版本的问题。不怎么用Python，只能查到这里了

**Comment by colawithsauce** [comment]
1.3.3 没有问题，最新版本有问题

**Comment by tonquer** [comment]
大概是pyinstaller打包时加了--strip导致的

**Comment by tonquer** [comment]
v1.3.5已发布，修复了这个问题
