### ISSUE TITLE
无法正常登陆

### ISSUE THREAD

**Issue by 1MrDes** [tonquer/picacg-qt#125]
### 操作系统（如MacOS 10.15）
>Win10

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>
电信宽带

### 问题描述（简要描述发生的问题）
>
无法登陆

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>
点击登陆就跳出

### 日志提交（问题截图或者日志，日志在logs目录）
>
2022-01-27 20:09:57,488 - tool.py[line:161] - ERROR: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "tools\tool.py", line 157, in ParseFromData
  File "json\__init__.py", line 348, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by 1MrDes** [comment]
![%DKXE`FD U94M)WHA DML](https://user-images.githubusercontent.com/31330694/151356889-5a7cce31-d39f-40b6-b296-3922b555d7bd.png)

**Comment by 1MrDes** [comment]
挂梯子就能上了 应该是网络问题 这是为什么呢？之前我可以WIFI直接上的

**Comment by 1MrDes** [comment]
尝试了修改 原来是我自己的问题
