### ISSUE TITLE
本月4号之后更新漫画图片的大部分加载不出来，是哔咔的问题吗

### ISSUE THREAD

**Issue by qwerty1874** [tonquer/picacg-qt#136]
日志中记录了

2022-03-04 13:52:35,432 - user_handler.py[line:240] - ERROR: [WinError 123] 文件名、目录名或卷标语法不正确。: 'E:/PicACG\\cache\\tobeimg/uQXszZmwpSmuaxRSZGj4qZ5KBWPuUCGt11jJTVtKSGQ/rs:fill:300:400:0'
Traceback (most recent call last):
  File "server\user_handler.py", line 234, in __call__
  File "os.py", line 213, in makedirs
  File "os.py", line 223, in makedirs
OSError: [WinError 123] 文件名、目录名或卷标语法不正确。: 'E:/PicACG\\cache\\tobeimg/uQXszZmwpSmuaxRSZGj4qZ5KBWPuUCGt11jJTVtKSGQ/rs:fill:300:400:0'

全是这样的错误

谢谢大佬的无私奉献，好人一生平安

**Comment by tonquer** [comment]
哔咔最新改了新图片的域名，
如果没fq的话，你可以自己修改系统hosts，把storage-b.picacomic.com指向104.20.180.50或者自定义CDN ip，
可以暂时解决部分封面加载失败的问题。

**Comment by qwerty1874** [comment]
> 哔咔最新改了新图片的域名， 如果没fq的话，你可以自己修改系统hosts，把 storage-b.picacomic.com 指向104.20.180.50或者自定义CDN ip， 可以暂时解决部分封面加载失败的问题。

**Comment by qwerty1874** [comment]
谢谢大佬
