### ISSUE TITLE
能否提供一个requirements.txt

### ISSUE THREAD

**Issue by yangmagua** [tonquer/picacg-qt#175]
### 能否提供一个requirements.txt
我在尝试git源码时想添加新功能pr的时候安装最新版PySide6并没法运行，报错如下

Traceback (most recent call last):
  File "C:/Users/16917/Desktop/picacg-qt-main/src/start.py", line 12, in <module>
    from qt_error import showError
  File "C:\Users\16917\Desktop\picacg-qt-main\src\qt_error.py", line 3, in <module>
    from PySide6.QtCore import Qt
  File "C:\Users\16917\AppData\Local\Programs\Python\Python38\lib\site-packages\PySide6\__init__.py", line 143, in <module>
    _setupQtDirectories()
  File "C:\Users\16917\AppData\Local\Programs\Python\Python38\lib\site-packages\PySide6\__init__.py", line 64, in _setupQtDirectories
    from shiboken6 import Shiboken
  File "C:\Users\16917\AppData\Local\Programs\Python\Python38\lib\site-packages\shiboken6\__init__.py", line 25, in <module>
    from shiboken6.Shiboken import *
ImportError: DLL load failed while importing Shiboken: 找不到指定的程序。

如果有requirements我或许会更好的定位问题

**Comment by tonquer** [comment]
src/requirements.txt

**Comment by tonquer** [comment]
win7的qt版本必须6.1.3

**Comment by yangmagua** [comment]
> win7的qt版本必须6.1.3

我现在是window10 python3.8 创建了一个虚拟环境来安装库，指令是pip install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple
但是还是报错ImportError: DLL load failed while importing Shiboken: 找不到指定的程序。
我现在打算尝试python降级到3.6进行尝试

**Comment by yjrqz777** [comment]
python版本要大于3.8.0，一定不能是3.8.0，我更新到3.8.5就可以了

**Comment by yjrqz777** [comment]
![image](https://github.com/tonquer/picacg-qt/assets/76079782/f5186047-186c-46fb-81a6-09fbfebbf3b4)
