### ISSUE TITLE
想知道archlinux怎么安装这个软件

### ISSUE THREAD

**Issue by assdrf** [tonquer/picacg-qt#234]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 
我在aur里安装了
但是打开提示错误
### 附加信息（其他的与功能相关的附加信息）
> 
Traceback (most recent call last):
 File "/usr/share/picacg-qt/start.py", line 83, in <module>
  main = MainView()
 File "/usr/share/picacg-qt/view/main/main_view.py", line 31, in __init__
  Main.__init__(self)
 File "/usr/share/picacg-qt/component/widget/main_widget.py", line 66, in __init__
  self.setupUi(self)
 File "/usr/share/picacg-qt/interface/ui_main.py", line 99, in setupUi
  self.indexView = IndexView()
 File "/usr/share/picacg-qt/view/index/index_view.py", line 17, in __init__
  self.setupUi(self)
 File "/usr/share/picacg-qt/interface/ui_index.py", line 39, in setupUi
  self.randomList = ComicListWidget(self.tab_1)
 File "/usr/share/picacg-qt/component/list/comic_list_widget.py", line 22, in __init__
  self.setFrameShape(self.NoFrame) # 无边框
AttributeError: 'ComicListWidget' object has no attribute 'NoFrame'

### 效果演示（可以提供可借鉴的图片）
>

**Comment by tonquer** [comment]
你无法直接打开AppImage吗

**Comment by assdrf** [comment]
> 你无法直接打开AppImage吗
改为使用AppImage解决了这个问题
