### ISSUE TITLE
挂梯子无法登录

### ISSUE THREAD

**Issue by uneofus** [tonquer/picacg-qt#240]
2023-03-21 12:32:38,168 - tool.py[line:161] - ERROR: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "src\util\tool.py", line 157, in ParseFromData
  File "json\__init__.py", line 348, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by uneofus** [comment]
> 2023-03-21 12：32：38，168 - tool.py[行：161] - 错误：预期值：第 1 行第 1 列（字符 0） 回溯（最近最后一次调用）：文件 “src\util\tool.py”，第 157 行，在 ParseFromData 中 文件 “json__init__.py”，第 348 行，加载中 文件“json\decoder.py”，第 337 行，解码 文件 “json\decoder.py”，第 355 行，在 raw_decode json.decoder.JSONDecodeError：预期值：第 1 行第 1 列（字符 0）



>
