### ISSUE TITLE
不能登录

### ISSUE THREAD

**Issue by laiyoi** [tonquer/picacg-qt#273]
### 操作系统（如MacOS 10.15）
>
win10

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>
联通宽带

### 问题描述（简要描述发生的问题）
>
![image](https://github.com/tonquer/picacg-qt/assets/117524251/6b437211-bbbd-4747-9b36-141753831e82)

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>
点击登录

### 日志提交（问题截图或者日志，日志在设置中设置为INFO，在帮助界面打开日志目录）
>
![image](https://github.com/tonquer/picacg-qt/assets/117524251/8363006a-9f49-4243-bb51-d2544389e945)
```
2023-09-17 14:51:26,305 - start.py[line:76] - WARNING: init scene ratio: 1.0
2023-09-17 14:51:26,557 - download_db.py[line:45] - WARNING: duplicate column name: tick Unable to execute statement
2023-09-17 14:51:27,743 - setting_view.py[line:307] - INFO: Init translate zh_CN
2023-09-17 14:51:27,829 - server.py[line:196] - INFO: request-> backId:1, InitReq, url:http://68.183.234.72/init, method:GET, params:{}
2023-09-17 14:51:27,829 - setting_view.py[line:467] - WARNING: waifu2x GPU: ['NVIDIA GeForce RTX 4070'],select: NVIDIA GeForce RTX 4070,use cpu num: 6
2023-09-17 14:51:27,830 - main_view.py[line:179] - WARNING: Waifu2x init:0, encode:0, version:1.1.6, code:0, cpuNum:6/8, gpuNum:8, gpuList:['NVIDIA GeForce RTX 4070']
2023-09-17 14:51:27,831 - server.py[line:196] - INFO: request-> backId:2, CheckPreUpdateReq, url:http://api.github.com/repos/tonquer/picacg-qt/releases, method:GET, params:{}
2023-09-17 14:51:27,865 - login_proxy_widget.py[line:335] - INFO: update proxy, apiSetId:4, imgSetID:4, image server:162.159.58.10, address:162.159.58.10
2023-09-17 14:51:27,884 - server.py[line:231] - INFO: response-> backId:2, CheckPreUpdateReq, st:1001, code:0
2023-09-17 14:51:27,894 - server.py[line:196] - INFO: request-> backId:3, CheckPreUpdateReq, url:http://api.ggo.icu/repos/tonquer/picacg-qt/releases, method:GET, params:{}
2023-09-17 14:51:28,592 - server.py[line:231] - INFO: response-> backId:3, CheckPreUpdateReq, st:1001, code:0
2023-09-17 14:51:29,510 - tool.py[line:173] - ERROR: <html>

<head><title>400 Bad Request</title></head>

<body bgcolor="white">

<center><h1>400 Bad Request</h1></center>

<hr><center>nginx/1.14.0 (Ubuntu)</center>

</body>

</html>

Traceback (most recent call last):
  File "tools\tool.py", line 169, in ParseFromData
  File "json\__init__.py", line 348, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2023-09-17 14:51:29,512 - server.py[line:231] - INFO: response-> backId:1, InitReq, st:1001, code:0
2023-09-17 14:51:29,512 - user.py[line:83] - ERROR: 'BaseRes' object has no attribute 'status'
Traceback (most recent call last):
  File "tools\user.py", line 63, in InitBack
AttributeError: 'BaseRes' object has no attribute 'status'
2023-09-17 14:51:29,552 - server.py[line:196] - INFO: request-> backId:4, LoginReq, url:http://picaapi.picacomic.com/auth/sign-in, method:POST, params:{'email': 'zz15091429981', 'password': '******'}
2023-09-17 14:51:29,555 - server.py[line:35] - INFO: dns parse, host:picaapi.picacomic.com->162.159.58.10
2023-09-17 14:51:29,838 - server.py[line:231] - INFO: response-> backId:4, LoginReq, st:1001, code:500
2023-09-17 14:51:29,839 - user.py[line:130] - INFO: 登陆失败！！！, userId:zz15091429981, code:500, text:{"code":500,"error":"MISCONF Redis is configured to save RDB snapshots, but it is currently not able to persist on disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.","message":"--","detail":":("}
2023-09-17 14:51:30,771 - favorite_view.py[line:154] - INFO: load favorite page:1
2023-09-17 14:51:30,771 - server.py[line:196] - INFO: request-> backId:5, FavoritesReq, url:http://picaapi.picacomic.com/users/favourite?s=da&page=1, method:GET, params:{}
2023-09-17 14:51:30,948 - server.py[line:231] - INFO: response-> backId:5, FavoritesReq, st:1001, code:500
2023-09-17 14:51:30,951 - favorite_view.py[line:238] - ERROR: 'total'
Traceback (most recent call last):
  File "view\user\favorite_view.py", line 209, in UpdatePagesBack
KeyError: 'total'
2023-09-17 14:51:30,952 - favorite_view.py[line:154] - INFO: load favorite page:1
2023-09-17 14:51:30,952 - server.py[line:196] - INFO: request-> backId:6, FavoritesReq, url:http://picaapi.picacomic.com/users/favourite?s=da&page=1, method:GET, params:{}
2023-09-17 14:51:31,114 - server.py[line:231] - INFO: response-> backId:6, FavoritesReq, st:1001, code:500
2023-09-17 14:51:31,114 - favorite_view.py[line:238] - ERROR: 'total'
Traceback (most recent call last):
  File "view\user\favorite_view.py", line 209, in UpdatePagesBack
KeyError: 'total'
2023-09-17 14:51:31,115 - favorite_view.py[line:154] - INFO: load favorite page:1
2023-09-17 14:51:31,115 - server.py[line:196] - INFO: request-> backId:7, FavoritesReq, url:http://picaapi.picacomic.com/users/favourite?s=da&page=1, method:GET, params:{}
2023-09-17 14:51:31,286 - server.py[line:231] - INFO: response-> backId:7, FavoritesReq, st:1001, code:500
2023-09-17 14:51:31,286 - favorite_view.py[line:238] - ERROR: 'total'
Traceback (most recent call last):
  File "view\user\favorite_view.py", line 209, in UpdatePagesBack
KeyError: 'total'
2023-09-17 14:51:31,287 - favorite_view.py[line:154] - INFO: load favorite page:1
2023-09-17 14:51:31,287 - server.py[line:196] - INFO: request-> backId:8, FavoritesReq, url:http://picaapi.picacomic.com/users/favourite?s=da&page=1, method:GET, params:{}
2023-09-17 14:51:31,472 - server.py[line:231] - INFO: response-> backId:8, FavoritesReq, st:1001, code:500
2023-09-17 14:51:31,473 - favorite_view.py[line:238] - ERROR: 'total'
Traceback (most recent call last):
  File "view\user\favorite_view.py", line 209, in UpdatePagesBack
KeyError: 'total'
2023-09-17 14:51:31,473 - favorite_view.py[line:154] - INFO: load favorite page:1
2023-09-17 14:51:31,474 - server.py[line:196] - INFO: request-> backId:9, FavoritesReq, url:http://picaapi.picacomic.com/users/favourite?s=da&page=1, method:GET, params:{}
2023-09-17 14:51:31,655 - server.py[line:231] - INFO: response-> backId:9, FavoritesReq, st:1001, code:500
2023-09-17 14:51:31,655 - favorite_view.py[line:238] - ERROR: 'total'
Traceback (most recent call last):
  File "view\user\favorite_view.py", line 209, in UpdatePagesBack
KeyError: 'total'
```

**Comment by nahidaspuripuri** [comment]
主站服务端炸了，应该不是应用的问题

**Comment by tonquer** [comment]
非本应用的问题
