### ISSUE TITLE
未登录时点击签到出现连续虚空签到且无法终止

### ISSUE THREAD

**Issue by sink-er** [tonquer/picacg-qt#303]
### 操作系统（如MacOS 10.15）
>
windows11 23H2
操作系统版本 22631.3527

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>
移动宽带。

### 问题描述（简要描述发生的问题）
>
在未登录情况下，点击签到会出现连续虚空签到，且无法终止，只能通过任务管理器关闭。

https://github.com/tonquer/picacg-qt/assets/53322400/02901d64-5ef8-4b57-ac0e-18f0bb2e6a5a

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>
在未登录情况下，点击签到

### 日志提交（问题截图或者日志，日志在设置中设置为INFO，在帮助界面打开日志目录）
>
2024-05-05 03:48:00,966 - start.py[line:77] - WARNING: init scene ratio: 1.5
2024-05-05 03:48:01,338 - download_db.py[line:45] - WARNING: duplicate column name: tick Unable to execute statement
2024-05-05 03:48:03,717 - setting_view.py[line:476] - WARNING: waifu2x GPU: ['NVIDIA GeForce GTX 1660 Ti'],select: NVIDIA GeForce GTX 1660 Ti,use cpu num: 0
2024-05-05 03:48:03,719 - main_view.py[line:194] - WARNING: Waifu2x init:0, encode:0, version:1.1.6, code:0, cpuNum:0/8, gpuNum:8, gpuList:['NVIDIA GeForce GTX 1660 Ti']
2024-05-05 03:48:12,273 - user_handler.py[line:120] - ERROR: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "server\user_handler.py", line 117, in __call__
  File "tools\user.py", line 169, in PunchedBack
TypeError: unsupported operand type(s) for +: 'int' and 'str'
2024-05-05 03:48:13,635 - user_handler.py[line:120] - ERROR: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "server\user_handler.py", line 117, in __call__
  File "tools\user.py", line 169, in PunchedBack
TypeError: unsupported operand type(s) for +: 'int' and 'str'
2024-05-05 03:48:14,124 - user_handler.py[line:120] - ERROR: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "server\user_handler.py", line 117, in __call__
  File "tools\user.py", line 169, in PunchedBack
TypeError: unsupported operand type(s) for +: 'int' and 'str'
2024-05-05 03:48:14,666 - user_handler.py[line:120] - ERROR: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "server\user_handler.py", line 117, in __call__
  File "tools\user.py", line 169, in PunchedBack
TypeError: unsupported operand type(s) for +: 'int' and 'str'
2024-05-05 03:48:15,136 - user_handler.py[line:120] - ERROR: unsupported operand

**Comment by tonquer** [comment]
https://github.com/tonquer/picacg-qt/releases/tag/v1.5.0
已修复
