### ISSUE TITLE
kde环境下程序无法启动

### ISSUE THREAD

**Issue by zzidun** [tonquer/picacg-qt#330]
### 操作系统（如MacOS 10.15）
>
Arch Linux +  Plasma 6.1.5 + wayland

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>

不涉及

### 问题描述（简要描述发生的问题）
>

无法启动, 报错

```
024-09-25 20:44:30,395 - main_widget.py[line:58] - ERROR: No module named 'xcffib'
Traceback (most recent call last):
  File "component/widget/main_widget.py", line 17, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "component/widget/qframelesswindow/__init__.py", line 21, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "component/widget/qframelesswindow/titlebar/__init__.py", line 8, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "component/widget/qframelesswindow/utils/__init__.py", line 9, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "component/widget/qframelesswindow/utils/linux_utils.py", line 4, in <module>
ModuleNotFoundError: No module named 'xcffib'
1002
2024-09-25 20:44:30,553 - download_db.py[line:45] - WARNING: duplicate column name: tick Unable to execute statement
920
QLayout: Attempting to add QLayout "" to QWidget "LineEditHelp", which already has a layout
QLayout: Attempting to add QLayout "" to QWidget "LineEditHelp", which already has a layout
qt.qpa.wayland: Failed to load client buffer integration: "wayland-egl"
qt.qpa.wayland: Available client buffer integrations: QList()
PySide6.QtCore.QSize(1920, 1080) PySide6.QtCore.QSize(1440, 866)
qt.qpa.wayland: No shell integration named "xdg-shell" found
qt.qpa.wayland: No shell integration named "wl-shell" found
qt.qpa.wayland: No shell integration named "ivi-shell" found
qt.qpa.wayland: Loading shell integration failed.
qt.qpa.wayland: Attempted to load the following shells QList("xdg-shell", "wl-shell", "ivi-shell")
PySide6.QtCore.QSize(1440, 866)
vkCreateInstance failed -9
vkCreateInstance failed -9
vkCreateInstance failed -9
2024-09-25 20:44:31,512 - setting_view.py[line:476] - WARNING: waifu2x GPU: None,select: CPU,use cpu num: 0
vkCreateInstance failed -9
2024-09-25 20:44:31,513 - main_view.py[line:196] - WARNING: Waifu2x init:-1, encode:-1, version:1.1.6, code:0, cpuNum:0/12, gpuNum:0, gpuList:None
qt.qpa.backingstore: composeAndFlush: QOpenGLContext creation failed
qt.qpa.backingstore: composeAndFlush: makeCurrent() failed

```

已经安装`xcffib`

```
Name: xcffib
Version: 1.5.0
Summary: A drop in replacement for xpyb, an XCB python binding
Home-page: http://github.com/tych0/xcffib
Author: Tycho Andersen
Author-email: tycho@tycho.pizza
License: Apache License 2.0
Location: /usr/lib/python3.12/site-packages
Requires: cffi
Required-by: 

```

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>

### 日志提交（问题截图或者日志，日志在设置中设置为INFO，在帮助界面打开日志目录）
>

**Comment by tonquer** [comment]
加sudo试试
